services:
  backend:
    build: ./backend
    ports:
      - "8090:8090"
    env_file:
      - .env

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - .env

  database:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
